version: "3.8"
services:
  postgres:
    image: postgres:14.3
    restart: always
    command: postgres -c 'max_connections=300'
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
      # Cached dependencies
      - ruby-bundle-cache-play-with-openapi-generator:/bundle
      # Ignore following directories from volume mount for better performance.
      - /rails/public
      - /rails/tmp
    ports:
      - "3001:3000"
    depends_on:
      - postgres

volumes:
  ruby-bundle-cache-play-with-openapi-generator:
